<template>
    <div class="creation" :class="locale">
        <div class="first-wrapper">
            <headline :firstLine="'Creators Recruitment'" :secondLine="'Program'"></headline>
            <div class="text-box">
                <p>Want to be a web3 art creator and need help figuring out where to start? HeartX is a one-stop solution to help you out. Whether you want to create a painting, PFP, photography, 3D modeling, video, or animation as an NFT artwork, start here and let your great artworks speak for you!</p>
<!--                <p class="text1">"What is StarryNight?</p>-->
<!--                <div class="regist-count">
                    <span>&nbsp;{{roleUsersStore.total.artists}}&nbsp;</span> <br>
                    creators already in residence <br>
                    <span class="text2">&nbsp;{{roleUsersStore.total.works}}&nbsp;</span> <br>
                    pieces of artwork
                </div>-->
            </div>
        </div>
        <div class="second-wrapper" v-if="addType === 1">
            <template v-if="userWorks.workslist.length>0">
                <middle-title :text="'My works'" id="swiperTop"></middle-title>
                <works-swiper-item :listData="userWorks.workslist" :showDelete="false" :onlyShowTit="true"
                    :titleStyle="{'textAlign': 'center','display': '-webkit-box','-webkit-box-orient': 'vertical','-webkit-line-clamp': 2,'overflow': 'hidden','word-break': 'break-all' }">
                </works-swiper-item>
            </template>
            <a @click.stop="router.push('/creation/add')" class="add-box">Upload an Artwork</a>
        </div>

        <div class="second-wrapper" v-else>
            <middle-title :text="'Upload an Artwork'"></middle-title>
            <add-work ref="addWorkComponent" @postNewWorks="postNewWorks"></add-work>
        </div>

        <!-- <div class="add-wrapper" v-else>
            <middle-title :text="'Add Work'"></middle-title>
            <add-works></add-works>
            <div class="add-box">Submit</div>
        </div> -->

        <div class="faq">
            <middle-title :text="'Frequently Asked Questions'"></middle-title>
            <ul>
                <li>
                    <div class="name">1、What is HeartX?</div>
                    <p>HeartX, a global Web3 artwork community and marketplace for artists, collectors & art lovers, is driven by community consensus. In the spirit of fostering emerging artists, it
                        redefines the value of art with Web 3 concepts & technologies and intends to bring investment value to global art creators and lovers.</p>
                </li>
                <li>
                    <div class="name">2、What will I get if I become an HeartX creator & artist?</div>
                    <p>HeartX is built on a global public chain environment. Blockchain technology helps artists to secure rights for physical and digital artworks, making the circulation of artworks
                        transparent and traceable; the creator of each transaction generated by an artwork receives a 5% royalty on the creation, and the artwork has both offline and online value.</p>
                </li>
                <li>
                    <div class="name">3、Are there any additional rewards for artists who have been enrolled in the product testing phase?</div>
                    <p>Artists invited to be residents at this stage will be directly certified by the platform as artists, and their artworks will be included to priority recommendation resources.
                        HeartX will also reward artists with tokens circulated by the platform. In addition, artists invited in this stage will receive additional platform token incentives if they rank
                        high in the HB system in the first month (specific details to be announced).</p>
                </li>
            </ul>
        </div>
        <page-footer></page-footer>
    </div>
</template>
<script setup>
import { ref, onMounted, nextTick } from 'vue'
import { storeToRefs } from 'pinia'
import $dialog from '@/views/components/dialog'
import Headline from '@/views/components/common-title/headline.vue'
import MiddleTitle from '@/views/components/common-title/middle-title.vue'
import WorksSwiperItem from '@/views/components/works-swiper-item/index.vue'
import PageFooter from '@/views/components/page-footer.vue'
import AddWork from '@/views/page/creation/add-work.vue'
import { useRoleUsersStore } from '@/store/role.js'
import {
    useUserStore,
    useMyworksStore,
    useAddWorkStore,
    useInviteStore
} from '@/store/user.js'
const roleUsersStore = useRoleUsersStore()
const userStore = useUserStore()
const userWorks = useMyworksStore()
const addWorkStore = useAddWorkStore()
const useInvite = useInviteStore()

const getMyworks = async () => {
    await userWorks.getMyworks()
}

const addType = ref(1) // 1: 默认展示作品列表；2: 新增作品

router.beforeEach((to, from) => {
    addType.value = to.path === '/creation' ? 1 : 2
})
const addWorkComponent = ref(null)
const postNewWorks = async (formData) => {
    if (!useInvite.inviteInfo && !!formData.code) {
        const bindStatus = await useInvite.bindInvite(formData.code)
        if (bindStatus) {
            await postNewWorks(formData)
        } else {
            addWorkComponent.value.resetSending()
            $dialog({
                type: 'warning',
                title: 'Invitation Code Is Invalid',
                content: ' '
                // btnText:'Confirm',
            })
        }
    } else {
        let newForm = {
            pfid: userStore.userinfo.pfid.toString(), //pfid	string	用户id，调用海洋那边接口后得到的用户id
            type: formData.type === 3 ? 2 : 1, //type	int	作品类型：1实物，2数字
            name: formData.name, //name	string	作品名称
            descr: formData.descr //descr	string	描述
        }
        if (formData.type === 3) {
            //NFT
            newForm.contract_address = formData.contract_address //NFT合约地址
        } else {
            newForm = {
                category: formData.category.id, //category	int	作品分类id，参见prepare的category_list
                create_y: formData.create_y.id, //create_y	int	创作年代id，参见prepare的create_y_list
                images: [], //images	图片, 数组	["https://aaa.com/a.jpg","https://aaa.com/a.jpg"]
                length: '', //length	int	长 ,单位cm或px
                width: '', //width	int	宽 ,单位cm或px
                height: '', //height	int	高 ,单位cm或px
                fi_size: '', //fi_size	string	首图的长宽,格式：（100,200）长,宽
                ...newForm
            }
            for (let i = 0; i < formData.images.length; i++) {
                if (formData.images[i].status === 'finish') {
                    if (newForm.images.length === 0) {
                        newForm.fi_size = formData.images[i].fi_size
                    }
                    newForm.images.push(formData.images[i].url)
                }
            }
            newForm.images = JSON.stringify(newForm.images)
        }
        addWorkStore.status = 'loading'
        const res = await addWorkStore.addWork(newForm)
        if (addWorkStore.status === 'success') {
            console.log('creation/Index.vue GET status Success')
            $dialog({
                type: 'success',
                title: 'Successfully Saved',
                content: 'Everything Is Working Normally.',
                callBack: (loading, closeFn) => {
                    closeFn()
                    setTimeout(() => {
                        router.push('/creation')
                    }, 500)
                }
            })
            /*$dialog({
                type: "success",
                callback(loading,closeFn){
                    console.log('add new work','go creation')
                    router.push('/creation');
                    closeFn();
                }
            });*/
        }
    }
}

// $dialog({type: "success"});
import { useI18n } from 'vue-i18n'
import router from '@/router/index.js'
const { locale, t } = useI18n()
const { roleUserlist, serverTime, total } = storeToRefs(roleUsersStore)
const getRoleUser = async () => {
    await roleUsersStore.getRoleUsersList()
}

onMounted(() => {
    if (userStore.userinfo.access_token) {
        getRoleUser()
        getMyworks()
        addType.value =
            router.currentRoute.value.path === '/creation/add' ? 2 : 1
    }
})
// const getMyWorks = async () => {
//     if (!userStore.userinfo.pfid) {
//         window.toast('You can view my works after logging in')
//     } else {
//         const res = await POST(`${window.api.api}/web/user/works`, null, {
//             'USER-PFID': userStore.userinfo.pfid,
//             'USER-TOKEN': userStore.userinfo.access_token
//         })
//         try {
//             if (res.ret_code === 0) {
//                 worksList.value = res.data.list
//             } else {
//                 window.toast(res.ret_code)
//             }
//         } catch (e) {}
//     }
// }
</script>
<style lang="scss" scoped>
.creation {
    background: linear-gradient(
            to bottom,
            rgb(255, 255, 255, 0) 25%,
            rgb(255, 255, 255, 0.98) 75%
    ),
    url('@/assets/images/creation/bg.png') no-repeat center top/100% auto;
    .first-wrapper {
        width: 100vw;
        padding-top: 167px;
        overflow: hidden;
    }
    .text-box {
        margin: 75px auto;
        width: 1140px;
        font-style: normal;
        font-weight: 400;
        font-size: 20px;
        line-height: 160%;
        text-align: center;
        color: #000000;
        .text1 {
            font-style: italic;
            font-weight: 900;
            line-height: 160%;
            color: #505050;
            vertical-align: baseline;
            margin-bottom: 45px;
        }
        .regist-count {
            span {
                display: inline-block;
                font-style: italic;
                font-weight: 900;
                font-size: 38px;
                line-height: 120%;
                color: #505050;
                vertical-align: baseline;
                &.text2 {
                    margin-top: 20px;
                }
            }
        }
    }
    .second-wrapper {
        :deep(.works-box) {
            .works-box-swiper {
                height: 358px;
            }
        }
    }
    .add-box {
        display: block;
        text-decoration: none;
        margin: 58px auto 0;
        gap: 8px;
        width: 340px;
        height: 75px;
        line-height: 75px;
        background: linear-gradient(285.35deg, #3bdecd 16.94%, #f365ac 85.12%);
        border-radius: 50px;
        text-align: center;
        font-style: normal;
        font-weight: 700;
        font-size: 24px;
        text-transform: capitalize;
        color: #ffffff;
        cursor: pointer;
    }
    .faq {
        margin: 159px auto 0;
        width: 1139px;
        ul {
            margin-top: 94px;
            li {
                margin-bottom: 104px;
                font-style: normal;
                .name {
                    margin-bottom: 20px;
                    font-weight: 800;
                    font-size: 24px;
                    line-height: 120%;
                    color: rgba(0, 0, 0, 0.75);
                }
                p {
                    font-weight: 400;
                    font-size: 20px;
                    line-height: 160%;
                    color: #000000;
                }
            }
        }
    }
    .add-wrapper {
        margin-top: -265px;
    }
}
@media only screen and (min-width: 2001px) {
    // xxxl
    .creation {
        .text-box {
            width: 1440px;
            font-size: 24px;
        }
        .second-wrapper {
            //margin-top: -240px;
        }
        .faq {
            width: 1440px;
            ul {
                li {
                    .name {
                        font-size: 26px;
                    }
                    p {
                        font-size: 22px;
                    }
                }
            }
        }
    }
}
@media only screen and (max-width: 2000px) {
    // xxl
}
@media only screen and (max-width: 1600px) {
    // xl
}
@media only screen and (max-width: 1200px) {
    // lg
    .creation {
        .first-wrapper {
        }
        .text-box {
            width: 1000px;
            .style-none {
                display: none;
            }
        }
        .second-wrapper {
            :deep(.works-box) {
                .works-box-swiper {
                    height: 29.83333333vw;
                }
            }
        }
    }
}
@media only screen and (max-width: 1024px) {
    // md
    .creation {
        .text-box {
            width: 90vw;
            .regist-count {
                span {
                    font-size: 36px;
                }
            }
            .style-none {
                display: none;
            }
        }
        .second-wrapper {
        }
        .faq {
            width: 890px;
            ul {
                li {
                    .name {
                        font-size: 22px;
                    }
                    p {
                        font-size: 18px;
                    }
                }
            }
        }
    }
}
@media only screen and (max-width: 768px) {
    // sm
    .creation {
        .first-wrapper {
        }
        .faq {
            width: 89%;
        }
        .text-box {
            width: 89%;
        }
        .second-wrapper {
            :deep(.works-box) {
                .works-box-swiper {
                    height: 39.5360725vw;
                }
            }
        }
        .add-box {
            width: 220px;
            height: 50px;
            line-height: 50px;
            font-size: 15px;
        }
    }
}
@media only screen and (max-width: 600px) {
    // xs
    .creation {
        background: linear-gradient(
                to bottom,
                rgb(255, 255, 255, 0) 25%,
                rgb(255, 255, 255, 0.98) 75%
        ),
        url('@/assets/images/creation/creation-m-bg.png') no-repeat
        center top/100% auto;
        .first-wrapper {
            padding-top: 86px;
        }
        .text-box {
            margin: 46px auto 0;
            /* width: 89%; */
            font-size: 15px;
            .text1 {
                font-size: 16px;
            }
            .regist-count {
                span {
                    font-size: 32px;
                }
            }
        }

        .second-wrapper {
            :deep(.works-box) {
                .works-box-swiper {
                    height: 58.6666666vw;
                }
            }
        }
        .add-box {
            margin-top: 40px;
        }
        .faq {
            width: 89%;
            margin-top: 75px;
            :deep(.title) {
                font-size: 32px;
                line-height: 37px;
                /* or 116% */
                background: linear-gradient(
                    180deg,
                    #000000 0%,
                    #757575 113.64%
                );
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
                text-fill-color: transparent;
            }
            ul {
                margin-top: 27px;
                li {
                    margin-bottom: 48px;
                    .name {
                        font-size: 22px;
                        text-align: center;
                        line-height: 160%;
                        margin-bottom: 36px;
                    }
                    p {
                        font-size: 15px;
                        text-align: center;
                    }
                }
            }
        }
    }
}
</style>
